# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: git@github.com:lincc-frameworks/python-project-template.git
author_email: adamschilperoort@gmail.com
author_name: uasal
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: false
mypy_type_checking: basic
package_name: tools_pearl
project_license: MIT
project_name: tools_pearl
project_organization: uasal
python_versions:
- '3.9'
- '3.10'
- '3.11'
